# Generated by Django 4.1.13 on 2025-05-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='subject',
            field=models.CharField(default='reservation', max_length=255),
        ),
    ]
