# Generated by Django 4.1.13 on 2025-05-05 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0009_remove_chatroom_admin_remove_chatroom_customer_and_more'),
        ('chat', '0002_chatroom_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.CharField(choices=[('community', 'Community Chat'), ('private', 'Private Chat')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='backend.postcommunity'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('system', 'System')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['chat_type'], name='chat_chatro_chat_ty_037291_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='chat_messag_message_973666_idx'),
        ),
    ]
