# Generated by Django 4.1.13 on 2025-05-05 03:41

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_chat_type_chatroom_community_message_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', validators=[chat.models.validate_image_size]),
        ),
    ]
