# Generated by Django 5.2 on 2025-05-18 16:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unread_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
