# Generated by Django 5.2 on 2025-05-18 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_unread_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_chat_ro_450d5a_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room'], name='chat_messag_chat_ro_acf3ae_idx'),
        ),
    ]
