# Generated by Django 5.2 on 2025-05-18 17:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_chat_messag_chat_ro_450d5a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unread_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, default=list, size=None),
        ),
    ]
